[package]
name = "ambl-example-cargo-builder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"

[dependencies.ambl-api]
git = "https://github.com/timbertson/ambl"
branch = "wit"
# rev = "0fd246da2e38bd39dd44e14d85a31f61e76ee3a3"
