[workspace]
members = [ "common", "api", "builder", "runtime", "builtin/cargo" ]

[profile.release]
panic = "abort"
lto = true # this is slow, but drops wasm sizes by ~80%

[profile.release.package.ambl-builtin-cargo]
opt-level = "z" # Optimize for size.
codegen-units = 1
