[package]
name = "ambl-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1"

[dev-dependencies]
ambl-common = { path = "../common" }
ambl-api = { path = "../api" }
anyhow = "1"
