package ambl:build

world builder {
  import ambllog: func(level: u8, msg: string)
  import amblinvoke: func(dep: string) -> string

  export version: func() -> u8
  export init: func(loglevel: u8)

  export rules: func(symbol: string, ctx: string) -> string
  export build: func(symbol: string, ctx: string) -> string
}
